Data:
  train_data_root: "/data1/zww/abaw/EXPR_splits_w100_s50/Train_Set"
  val_data_root: "/data1/zww/abaw/EXPR_splits_w100_s50/Validation_Set"
  loader:
    batch_size: 32
    num_workers: 4
    pin_memory: True
  norm: False

Model:
  model_name: Model
  bin_num: 1
  num_head: 4
  num_layer: 8
  kernel_size: 5
  out_dim: 512
  # pretrained_path: "log/fold1/ckpt_epoch_3_iter_94.pt"


Log:
  log_file_path: "./log/"
  log_file_name: "fold1_w100_s50.log"

Solver:
  loss: cross_entropy 
  epoch: 10
  warmup: 2
  lr: 0.00003 #0.00003
  weight_decay: 0.00001
  optimizer: AdamW
  dropout: 0.0
  label_smooth: 0.0
